name: utilx_mobile
description: "🔧 Contains mobile specific utility tools used in Dart projects related to Yukino Org."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter_inappwebview: ^5.3.2
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
