name: utilx
description: Custom utility tools.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    meta: ^1.7.0

dev_dependencies:
    devx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: devx
    lint: ^1.5.3
