name: extensions
description: Exposes the extensions system of Yukino.
version: 1.0.4

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    extensions_metadata:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: extensions_metadata
    extensions_runtime:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: extensions_runtime
    http: ^0.13.3
    utilx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: utilx

dev_dependencies:
    devx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: devx
    lint: ^1.5.3
