name: extensions_dev_tools
description: Consists of developer tools for Yukino extensions.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    colorize: ^3.0.0
    extensions:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: extensions
    hetu_script_dev_tools: ^0.0.8
    path: ^1.8.0
    utilx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: utilx

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-app/packages.git
            ref: devx
    lint: ^1.0.0
