name: Code Analysis (Dart UtilX Mobile)

on:
    push:
        branches:
            - dart_utilx_mobile
    workflow_dispatch:

jobs:
    dart-analyze:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dart_utilx_mobile

            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"

            - name: 🚧 Do prerequisites
              run: |
                  flutter pub get

            - name: 🩺 Check code format
              run: flutter format --output=none --set-exit-if-changed .

            - name: 🩺 Analyze code
              run: flutter analyze
