name: Documentation

on:
    push:
        branches:
            - dart_devx
            - dart_tenka_dev_tools
            - dart_tenka_runtime
            - dart_tenka_tenka
            - dart_tenka_utilx
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Build docs
              run: ./docs.sh

            - name: 🚀 Push docs
              uses: zyrouge/gh-push-action@v1.0.9
              with:
                  directory: docs
                  branch: gh-pages
